// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgYWu-atppDLvL3g24IpEqlYeNX7YLXGM',
    appId: '1:100661327282:android:257283bf323f8b463760ab',
    messagingSenderId: '100661327282',
    projectId: 'soleseekers-b07f2',
    databaseURL: 'https://soleseekers-b07f2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soleseekers-b07f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD7GAYPbMj3gOZlKoXE0c-GkWBLu_xLck',
    appId: '1:100661327282:ios:4f28ff7ca3fc1af53760ab',
    messagingSenderId: '100661327282',
    projectId: 'soleseekers-b07f2',
    databaseURL: 'https://soleseekers-b07f2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soleseekers-b07f2.appspot.com',
    androidClientId: '100661327282-r3v1vvb9fqk5mf860t37345oujpd5cl7.apps.googleusercontent.com',
    iosClientId: '100661327282-akekm7el3laahrod4s0vu0d349e3b704.apps.googleusercontent.com',
    iosBundleId: 'com.example.soleSeekers10',
  );
}
